[font]
size = 10

[cursor]
style = "Block"

# [font.normal]
# family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9

[colors.primary]
background = "#232136"
foreground = "#e0def4"

[colors.normal]
black   = "#393552"
red     = "#eb6f92"
green   = "#9ccfd8"
yellow  = "#f6c177"
blue    = "#c4a7e7"
magenta = "#ea9a97"
cyan    = "#9ccfd8"
white   = "#e0def4"

[colors.bright]
black   = "#6e6a86"
red     = "#eb6f92"
green   = "#9ccfd8"
yellow  = "#f6c177"
blue    = "#c4a7e7"
magenta = "#ea9a97"
cyan    = "#9ccfd8"
white   = "#e0def4"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

